{"timestamp":"2025-08-13T15:56:15.233784","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-13T15:56:15.235231","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-13T15:56:16.098468Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:56:16.101724Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:56:16.103441Z","level":"info","event":"Current task name:load_ratings","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:56:16.104324Z","level":"info","event":"Dag name:csv_ingestion_split_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:57:52.736829","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-08-13T15:57:52.766080","level":"warning","event":"Skipping masking for a secret as it's too short (<5 chars)","logger":"airflow.sdk.execution_time.secrets_masker"}
{"timestamp":"2025-08-13T15:57:52.766493","level":"info","event":"Connection Retrieved 'my_postgres'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-13T15:57:52.783358","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"postgres\" (172.18.0.4), port 5432 failed: FATAL:  database \"netflix_data\" does not exist\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/modules/load_data.py","lineno":52,"name":"load_csv_to_postgres"},{"filename":"/opt/airflow/modules/load_data.py","lineno":19,"name":"get_postgres_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}]}]}
{"timestamp":"2025-08-13T15:57:52.785699Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:57:52.790045Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:57:52.791805Z","level":"info","event":"Task:<Task(PythonOperator): load_ratings>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:57:52.792611Z","level":"info","event":"Failure caused by connection to server at \"postgres\" (172.18.0.4), port 5432 failed: FATAL:  database \"netflix_data\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-13T15:57:52.793357Z","level":"info","event":"","chan":"stdout","logger":"task"}
